[workspace]
resolver = "2"
members = ["mlml-dataset", "mlml-model", "mlml-util"]

[workspace.package]
license = "CC0-1.0"
readme = "README.md"

[workspace.dependencies]
rusqlite = "0.37"
serde = { version = "1.0.218", features = ["std", "derive"] }
serde_json = "1.0.140"
